### DISCUSSION TITLE
[Helm] Publishing helm chart on github pages

### DISCUSSION THREAD

**Discussion by AndreaGiardini** [developmentseed/titiler#316] [Feature Request]
Hey everyone :wave: 

It would be nice to publish the helm chart on github pages or something like that. This would make k8s installation much easier and help with adoption.

I am willing to help with this issue. Let me know how can I help

**Comment by vincentsarago** [comment]
Hi @AndreaGiardini, 
Thanks for starting the discussion. Please feel free to start something 🙏

**Comment by alexgleith** [comment]
Did we make any progress on this?

**Reply by vincentsarago** [reply]
I don't think so

**Comment by alexgleith** [comment]
For future reference, I was able to get the charts deployed using Flux with this configuration of a `GitRepository`

```
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: titiler
  namespace: titiler
spec:
  interval: 1m
  url: https://github.com/developmentseed/titiler/
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/deployment/k8s/charts/
```
