### DISCUSSION TITLE
Support for TMS/XYZ inputs - not only COGs

### DISCUSSION THREAD

**Discussion by jo-chemla** [developmentseed/titiler#640] [Q&A] [answered]
Hey there, probably a bad idea, if so please disregard and close the request!
I'm looking to build a browser, client-side, tiles downloader - which would eg be the equivalent to
 - Qgis `Save Raster Layer as` on a TMS raster source with given resolution and extent
 - or Gdal `gdal_translate -projwin minx maxy maxx miny -projwin_srs EPSG:4326 -outsize 4096 0 source_tms.xml output_4096.tif` where the `source_tms.xml` references the `ServerUrl` as shown in [this post](https://medium.com/planet-stories/a-gentle-introduction-to-gdal-part-3-geodesy-local-map-projections-794c6ff675ca)

At  the moment, I can reproduce this in TiTiler for an input COG using the `/cog/crop/{minx},{miny},{maxx},{maxy}[/{width}x{height}].{format}` GET endpoint from an input COG. Would love to be able to do this for a TMS/XYZ input as well, so I could use TiTiler as a middleware to download cropped images from TMS urls. 
I could try using [loam](https://www.azavea.com/blog/2021/05/03/introducing-loam-a-client-side-gdal-wrapper-for-javascript/) wasm gdal warper, but does not seem to support tms source inputs, same for geotiff-js. 
[Edit]: might be interesting to look at [gdal3.js](https://gdal3.js.org/docs/) which might accept TMS input sources while loam does not, but needs a little investigation.

**Comment by vincentsarago** [comment, marked as answer]
@jo-chemla there is no such thing as bad idea! 

It's already possible 😅, instead of passing a simple url (e.g `{endpoint}/tilejson.json?url=cog.tif`) you can pass a GDAL `wmts` string: https://titiler.xyz/cog/crop/-69.99510242702613,41.85313673098173,-69.99038118408833,41.857529724573766.png?url=WMTS%3Ahttp%3A%2F%2Ftitiler.xyz%2Fcog%2FWMTSCapabilities.xml%3Furl%3Dhttps%3A%2F%2Fnoaa-eri-pds.s3.amazonaws.com%2F2022_Pre_Event%2FEC2201a_OB_N_RGB%2FEC2201a_OB_N_C0700000w415145n.tif%26bidx%3D1%26bidx%3D2%26bidx%3D3%26tile_format%3Dpng&unscale=false&resampling=nearest&max_size=128&return_mask=true

see https://github.com/developmentseed/titiler/discussions/555#discussioncomment-4285690

**Reply by jo-chemla** [reply]
Woosh, looks exactly like what I need, thank you so much! Incredible all that can be done with TiTiler :)

**Reply by jo-chemla** [reply]
Sorry I think I got excited too quickly - before really decoding the url param with the wmts string. What I'd actually like to merge/crop are TMS/XYZ tiles with url like `http://domain.com/tileset_1/{z}/{x}/{y}.png` rather than a WMTS endpoint. 

I don't know lots of ways to transform a TMS url to a WMTS capable server - one is using mapproxy with the below config file [^1] for reference, but this would defeat the purpose of a pure client-side TMS/XYZ tiles merger/cropper.

So, by digging a bit the list of gdal raster drivers, I found the **TMS mini-driver** within the **WMS driver**. So I tried to use the following url, URL-encode it, and use it as the url param of the TiTiler crop endpoint, with no luck atm. Do you think I'm stepping in the right direction? 

Note the WMS strings are these of the gdal WMS driver example [here for osm](https://github.com/OSGeo/gdal/blob/master/frmts/wms/frmt_wms_openstreetmap_tms.xml) and [there for google](https://github.com/OSGeo/gdal/blob/master/frmts/wms/frmt_wms_googlemaps_tms.xml)

`WMS:<GDAL_WMS><Service name="TMS"><ServerUrl>http://domain.com/tileset_1/${z}/${x}/${y}</ServerUrl></Service><DataWindow><UpperLeftX>-20037508.34</UpperLeftX><UpperLeftY>20037508.34</UpperLeftY><LowerRightX>20037508.34</LowerRightX><LowerRightY>-20037508.34</LowerRightY><TileLevel>18</TileLevel><TileCountX>1</TileCountX><TileCountY>1</TileCountY><YOrigin>top</YOrigin></DataWindow><Projection>EPSG:3857</Projection><BlockSizeX>256</BlockSizeX><BlockSizeY>256</BlockSizeY><BandsCount>3</BandsCount><Cache /></GDAL_WMS>`



[^1]: 
  ```yaml

services:
  demo:
  tms:
    use_grid_names: true
    origin: 'nw'
  kml:
      use_grid_names: true
  wmts:
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: MapProxy serving custom XYZ scheme tiles.

layers:
  - name: layer_1
    title: layer_1
    sources: [cache_1]

caches:
  cache_1:
    grids: [osm_grid]
    sources: [source_1]

sources:
  source_1:
    type: tile
    url: http://domain.com/tileset_1/{z}/{x}/{y}.png
    grid: webmercator
```
