### ISSUE TITLE
k8s configuration

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler#212]
So I finally gave a try a k8s and my first feeling are not great 😬 

By talking with @geospatial-jeff it seems the default config are really low

https://github.com/developmentseed/titiler/blob/7eb21e63c817c4f39e15fae0ac95b3e9ad242c40/deployment/k8s/titiler/values.yaml#L41-L47

In addition to the k8s config, I think it's important to talk about the GDAL config, which seems to have a lot of implication on the performances.

cc @emmanuelmathot

**Comment by emmanuelmathot** [comment]
Indeed, our default helm chart values is more like

```yaml
  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 2
      memory: 4Gi
  env:
    PORT: 80
    CPL_TMPDIR: /tmp
    GDAL_CACHEMAX: 75%
    VSI_CACHE: TRUE
    VSI_CACHE_SIZE: 1073741824
    GDAL_DISABLE_READDIR_ON_OPEN: EMPTY_DIR
    GDAL_HTTP_MERGE_CONSECUTIVE_RANGES: YES
    GDAL_HTTP_MULTIPLEX: YES
    GDAL_HTTP_VERSION: 2
    PYTHONWARNINGS: ignore
    WEB_CONCURRENCY: 4
```
`WEB_CONCURRENCY` must be reduced due to the automatic calculation based on the CPU (/proc/cpu) that are always set to 16.

**Comment by geospatial-jeff** [comment]
This is our setup:

```yaml
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 1
    memory: 2Gi

env:
    CPL_TMPDIR: /tmp
    GDAL_CACHEMAX: 200 # 200 mb
    VSI_CACHE: TRUE
    VSI_CACHE_SIZE: 5000000 # 5 MB (per file-handle)
    GDAL_DISABLE_READDIR_ON_OPEN: EMPTY_DIR
    GDAL_HTTP_MERGE_CONSECUTIVE_RANGES: YES
    PYTHONWARNINGS: ignore
    WEB_CONCURRENCY: 2
```
